language: node_js
node_js:
  - "lts/*"
  - "node"

cache:
  yarn: true
  directories:
    - "node_modules"

jobs:
  include:
    - stage: "Code Format"
      node_js: "node"
    - script: yarn ts:lint
      name: "TS Lint"
    - script: yarn less:lint
      name: "LESS Lint"
    - script: yarn ts:format
      name: "Prettier Check"
    - stage: "Build"
      node_js: "node"
    - script: yarn build